<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZvIhLD\srcApp_KernelNDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZvIhLD/srcApp_KernelNDebugContainer.php') {
    touch(__DIR__.'/ContainerMZvIhLD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelNDebugContainer::class, false)) {
    \class_alias(\ContainerMZvIhLD\srcApp_KernelNDebugContainer::class, srcApp_KernelNDebugContainer::class, false);
}

return new \ContainerMZvIhLD\srcApp_KernelNDebugContainer([
    'container.build_hash' => 'MZvIhLD',
    'container.build_id' => '878b8dfe',
    'container.build_time' => 1592505716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZvIhLD');
