<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5miODc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5miODc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5miODc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5miODc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW5miODc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W5miODc',
    'container.build_id' => 'f54e0c17',
    'container.build_time' => 1593464820,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5miODc');
