<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeuqlLV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeuqlLV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDeuqlLV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDeuqlLV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDeuqlLV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DeuqlLV',
    'container.build_id' => 'd8677417',
    'container.build_time' => 1593293364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDeuqlLV');
